stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
    - data/raw/customer_churn.csv
    - src/data/preprocess.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
